"""update audit trai model

Revision ID: 80c710c5d200
Revises: 3eacf90caf4e
Create Date: 2026-04-30 14:00:38.806916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '80c710c5d200'
down_revision: Union[str, None] = '3eacf90caf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_requests', 'extension_requested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('consumables', 'hazardous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('containers', 'locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('documents', 'signature_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('documents', 'confidentiality_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('equipment', 'calibration_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('equipment', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('equipment', 'operational_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rfid_tags', 'tag_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('roles', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site_users', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sites', 'has_offline_capability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sites', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('storage_locations', 'temperature_controlled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('storage_locations', 'humidity_controlled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('storage_locations', 'access_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('studies', 'retention_period_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('system_settings', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_settings', 'is_editable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'is_editable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_settings', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('studies', 'retention_period_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage_locations', 'access_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('storage_locations', 'humidity_controlled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('storage_locations', 'temperature_controlled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sites', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sites', 'has_offline_capability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site_users', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('roles', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rfid_tags', 'tag_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('equipment', 'operational_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('equipment', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('equipment', 'calibration_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('documents', 'confidentiality_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('documents', 'signature_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('containers', 'locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('consumables', 'hazardous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('access_requests', 'extension_requested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
